#!/bin/bash
# Erik Martin-Dorel, 2018

set -e # exit on failure

pause() {
    read -r -s -n 1 -p "Press any key to ${1:-continue} (or ^C to exit)... "
    echo
}

srcdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )
repo="learn-ocaml"

if [ "$1" != "-B" ]; then
    cat >&2 <<EOF
Usage: ${BASH_SOURCE[0]} [-B]  # where -B runs 'make clean' beforehand
EOF
fi

export PS4='+ \e[36;1m(${0##*/} @ line $LINENO) \$\e[0m '
set -x # trace for debug

test -d "${srcdir}/../$repo" || git clone https://github.com/agrn/learn-ocaml.git -b ag/static-deploy --depth=1
cd "${srcdir}/../$repo/"
[ "$1" = "-B" ] && make clean
# make build
# make process-repo
make
make opaminstall
learn-ocaml build --repo=demo-repository
rsync -av --delete-delay www/ "${srcdir}"/docs
descr=$(git describe --long --always)

cd "${srcdir}"
cp -pv .nojekyll docs/
git add -v -A docs
git commit -m "Build $repo ($descr)" -e
pause push && git push
